language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: Nua2uvkKKlLX4IhfbbsdnG2y2Zwtcn305NRerZ5kuvnJLictrMW7I99nPCpA4RCGLIYaP/sn3E9oRVe1arl712DxGfWLx0j8seyU+hWczVIEJ7/RLVYkOexWI4nYYOaK3vnwXu9u0pJMYJXuuCmLZBDTKK16NbpXJg3kHgjK55FI80KK+NYC5VM6bgLO3ziBX9DZBGZKnoauDQ0ArTtjaYY1o+h36polIQ6oryPb6vF66bPVSVnaQ3EXguA3i3r71mqiUvFRjpmOP7KTbwTp4XDy3TOTkJXeduuL/+N4JTWD6zOR4C63lxNOPDLeb9ZlO7od6/9GKg+dCI/zVkrM0Iu6HEqf8neP/SqwYpX+82dj0m3R2Crse8xhATVUqg8z33fFi2Gcv8VmiP7M1W5FfKcSyfjNGJoemNrHI+b3nIqLmIy+/wm4fyHoM8RsK5f6MXeIJir9IkCiMJgIqwiiDE57+s9o5y64uxKB0hSUfgjVnua2sjMhvNprkAH52npuAxI6AlpztKigb0Cbjexqj7RnjjOpenPwcT53SlxY0mT+oDWcXFFz6tkyOxOPELMZwxfbyqBTm5J3fQeJFToWuxtAjFYkrG660GIDf9/p+ukrfCLYx5qq+qI4DW7N8WbiVqqXLYewpz3MgnXwLihb92W3GETG0JJppuM0vRmQk0M=
  on:
    tags: true
